### ISSUE TITLE
mysqld.sock 's softlink is not availble

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_mariadb#4]
src: /data/mysql/mysqld.sock
des: /data/mysql/mariadb.sock
But the link is not a file link:
![image](https://user-images.githubusercontent.com/16741975/102009837-279cfd80-3d75-11eb-9626-427e555607ea.png)

**Comment by qiaofeng1227** [comment]
all Unix socket file is display as this on SFTP, it is not a bug or issue
